### ISSUE TITLE
SinusBot not starting

### ISSUE THREAD

**Issue by RSWilli** [SinusBot/docker#38]
I started the sinusbot container using the following docker compose file:

```yaml
version: "3.7"
services:
  sinusbot:
    image: sinusbot/docker
    restart: unless-stopped
    ports:
      - 8087:8087
    volumes:
      - ./scripts:/opt/sinusbot/scripts
      - ./data:/opt/sinusbot/data
```

and the standard `docker-compose up` command

all I get in the logs is the following:

```
sinusbot_1  | Updating youtube-dl...
sinusbot_1  | youtube-dl is up-to-date (2020.09.14)
sinusbot_1  | User ID: 0
sinusbot_1  | Change file owner...
sinusbot_1  | Drop privileges...
sinusbot_1  | Starting SinusBot...
sinusbot_1  | PID: 11
sinusbot_1  | setpriv: libcap-ng is too old for "all" caps
```

it stops there

the instance is located behind an nginx reverse proxy using the config file from the documentation

if I try to connect to it, I only get an `application/octet-stream` answer, instead of the bot page

I even tried the tag `1.0.0-beta.10-202ee4d`, same issue there
